# Generated by Django 6.0.6 on 2026-06-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
