# Generated by Django 6.0.6 on 2026-06-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_description2_products_description3'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='warning',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
