# Generated by Django 6.0.6 on 2026-06-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='changer',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=4000),
        ),
    ]
