# Generated by Django 6.0.6 on 2026-06-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_products_changer_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
