# Generated by Django 6.0.6 on 2026-06-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_products_description4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
